feat: Creazione nuovo componente it-select
italia/design-angular-kit pull request #153
Opened 2022-12-24 14:54 UTC by cri99

## Descrizione

## Checklist

- [x] Le modifiche sono conformi alle [linee guida di design](https://design-italia.readthedocs.io/it/stable/index.html).
- [x] Il codice è coerente con le [indicazioni di progetto](https://italia.github.io/bootstrap-italia/docs/come-iniziare/).
- [x] Le modifiche sono state verificate sui [Browser supportati](https://getbootstrap.com/docs/4.0/getting-started/browsers-devices/) e per diverse risoluzioni dello schermo.
- [x] Sono stati effettuati test di accessibilità in ottemperanza a quanto descritto nell'[area "Accessibilità" delle linee guida di design](https://design-italia.readthedocs.io/it/stable/doc/service-design/accessibilita.html).
- [x] La documentazione è stata aggiornata.

2022-12-28 12:58 UTC, astagi requested changes
<img width="734" alt="image" src="https://user-images.githubusercontent.com/537363/209815861-1c41028d-2330-4a23-a9b5-f930dd8b37ca.png">

@cri99 ottimo lavoro, giusto un appunto il codice di alcuni esempi è indentato male.

2023-01-01 14:24 UTC, astagi commented
@cri99 ho mergiato i nuovi componenti su main almeno evitiamo di creare confusione :) questa PR per me è ok ma magari mergia il main e includi il nuovo componente (ed eventuali migliorie se servono) + test e documentazione, thanks!

2023-01-05 15:51 UTC, alenap93 commented
> <img alt="image" width="734" src="https://user-images.githubusercontent.com/537363/209815861-1c41028d-2330-4a23-a9b5-f930dd8b37ca.png">
> 
> @cri99 ottimo lavoro, giusto un appunto il codice di alcuni esempi è indentato male.

@astagi @cri99 fix riportata nell PR https://github.com/italia/design-angular-kit/pull/172

2023-01-09 10:37 UTC, astagi commented
> > <img alt="image" width="734" src="https://user-images.githubusercontent.com/537363/209815861-1c41028d-2330-4a23-a9b5-f930dd8b37ca.png">
> > @cri99 ottimo lavoro, giusto un appunto il codice di alcuni esempi è indentato male.
> 
> @astagi @cri99 fix riportata nella PR #172

Grazie mille @alenap93

2023-01-09 20:41 UTC, cri99 commented
Chiudo perché il componente select è stato già implementato nella versione già integrata di @AntoninoBonanno.

2023-01-09 20:41 UTC, closed without merging