Docs/269 pagination docs
italia/design-angular-kit pull request #298
Opened 2024-01-09 23:49 UTC by AntoninoBonanno

## Descrizione

- Close #269

## Checklist

- [ ] Le modifiche sono conformi alle [linee guida di design](https://design-italia.readthedocs.io/it/stable/index.html).
- [ ] Il codice è coerente con le [indicazioni di progetto](https://italia.github.io/bootstrap-italia/docs/come-iniziare/).
- [ ] Le modifiche sono state verificate sui [Browser supportati](https://getbootstrap.com/docs/4.0/getting-started/browsers-devices/) e per diverse risoluzioni dello schermo.
- [ ] Sono stati effettuati test di accessibilità in ottemperanza a quanto descritto nell'[area "Accessibilità" delle linee guida di design](https://design-italia.readthedocs.io/it/stable/doc/service-design/accessibilita.html).
- [ ] La documentazione è stata aggiornata.

2024-01-10 10:22 UTC, astagi commented
Grazie @AntoninoBonanno ci do un'occhiata asap

2024-01-10 13:36 UTC, astagi requested changes
@AntoninoBonanno mi succede una cosa strana, quando cambio pagina nella tabella, la colonna del nome si sposta. Occorre indagare sul perchè.

2024-01-13 15:50 UTC, AntoninoBonanno commented
@astagi il comportamento è corretto, poichè la tabella in bootstrap ha l'auto width. Infatti nelle altre pagine i nomi sono più corti e la prima colonna prende più spazio. (Ho provato ad aggiungere una pagina con i nomi della stessa lunghezza della prima pagina e il ridimensionamento non avviene)

Capisco che è fastidioso nell'esempio, quindi fisso la larghezza delle colonne

2024-01-15 09:59 UTC, astagi approved these changes

2024-01-15 10:00 UTC, merged